# Generated by Django 2.1.3 on 2018-12-03 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_ingredient', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('relation_with_person', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisposedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRequisitionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpanelledFirm',
            fields=[
                ('firm_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=50)),
                ('firm_email', models.EmailField(blank=True, max_length=254)),
                ('firm_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('present', models.BooleanField()),
                ('cured', models.BooleanField()),
                ('furthercomments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthCentreStaff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_type', models.CharField(choices=[('DR', 'Doctor'), ('PR', 'Pharmacist'), ('ST', 'Other staff'), ('MS', 'Medical Superintendent')], default='DR', max_length=2)),
                ('staff_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthCentreStaffContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_phone_no', models.CharField(max_length=10)),
                ('staff_email_id', models.EmailField(blank=True, max_length=254)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualRecord',
            fields=[
                ('person_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('ST', 'Student'), ('FA', 'Faculty'), ('SF', 'Staff')], default='ST', max_length=2)),
                ('password', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('manufacturing_company', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('SR', 'Syrup'), ('TB', 'Tablet'), ('OT', 'Ointment')], default='TB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_quantity', models.IntegerField()),
                ('issue_status', models.BooleanField()),
                ('non_issue_reason', models.TextField(blank=True)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('daignosis', models.TextField()),
                ('test_result', models.TextField()),
                ('follow_up_date', models.DateField()),
                ('follow_up_report', models.TextField()),
                ('isDependant', models.BooleanField()),
                ('testRecommended', models.BooleanField()),
                ('doctor_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
                ('patient_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.IndividualRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_serial_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_issue', models.DateField()),
                ('doctor_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
                ('patient_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.IndividualRecord')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('doctor_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff')),
                ('patient_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('requisition_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_of_order', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_of_approval', models.DateField()),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
                ('requisition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Requisition')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('batch_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('firm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.EmpanelledFirm')),
            ],
        ),
        migrations.CreateModel(
            name='StockMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('medicine_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Stock')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine')),
            ],
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='prescription_serial_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Prescription'),
        ),
        migrations.AddField(
            model_name='medicineissue',
            name='prescription_serial_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Prescription'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='patient_id',
            field=models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.PatientRecord'),
        ),
        migrations.AddField(
            model_name='doctorrequisitionproposal',
            name='doctor_id',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.HealthCentreStaff'),
        ),
        migrations.AddField(
            model_name='doctorrequisitionproposal',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine'),
        ),
        migrations.AddField(
            model_name='doctorrequisitionproposal',
            name='requisition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Requisition'),
        ),
        migrations.AddField(
            model_name='disposedmedicine',
            name='batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Requisition'),
        ),
        migrations.AddField(
            model_name='disposedmedicine',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine'),
        ),
        migrations.AddField(
            model_name='dependant',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.IndividualRecord'),
        ),
        migrations.AddField(
            model_name='composition',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Medicine'),
        ),
    ]
