# Generated by Django 2.1.3 on 2018-12-03 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedmedicine',
            name='date',
            field=models.DateField(default='2018-12-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disposedmedicine',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
