# Generated by Django 2.1.3 on 2018-12-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20181203_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineissue',
            name='non_issue_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
