# Generated by Django 2.1.3 on 2019-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20181203_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empanelledfirm',
            name='firm_phone',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('SR', 'Syrup'), ('TB', 'Tablet'), ('OT', 'Ointment'), ('IN', 'Injection'), ('SOL', 'Solution'), ('EQ', 'Equipment'), ('DEN', 'Dental'), ('CAP', 'Capsule'), ('OIL', 'Oil'), ('POW', 'Powder'), ('GA', 'Gargle'), ('OTH', 'Others')], default='TB', max_length=3),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturing_company',
            field=models.CharField(default='XX', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockmedicine',
            name='medicine_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
