# Generated by Django 2.1.3 on 2019-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190212_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcentrestaff',
            name='availability_from',
            field=models.CharField(default='0900', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcentrestaff',
            name='availability_to',
            field=models.CharField(default='1700', max_length=4),
            preserve_default=False,
        ),
    ]
