# Generated by Django 2.1.3 on 2019-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20190314_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecord',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff')], default='Student', max_length=2),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Syrup', 'Syrup'), ('Tablet', 'Tablet'), ('Ointment', 'Ointment'), ('Injection', 'Injection'), ('Solution', 'Solution'), ('Equipment', 'Equipment'), ('Dental', 'Dental'), ('Capsule', 'Capsule'), ('Oil', 'Oil'), ('Powder', 'Powder'), ('Gargle', 'Gargle'), ('Others', 'Others')], default='Tablet', max_length=3),
        ),
    ]
