# Generated by Django 2.1.3 on 2019-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20190314_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecord',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff')], default='Student', max_length=10),
        ),
    ]
