# Generated by Django 2.1.3 on 2019-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_studentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
