# Generated by Django 2.1.3 on 2019-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_auto_20190522_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineissue',
            name='medicine_quantity_issued',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
